/**
 * WebGIS SEPLAN Passo Fundo - Diagnósticos Territoriais
 * Catálogo Estruturado de Métricas e Indicadores Territoriais Oficiais
 * 
 * Regras Fundamentais de Governança dos Dados:
 * 1. Dados 100% reais, auditados sobre o acervo geoespacial do município.
 * 2. Classificação rigorosa de calculationStatus:
 *    - 'oficial': Diretamente fornecido pelo órgão oficial (IBGE, Lei Municipal, etc.)
 *    - 'calculado': Obtido por processamento geométrico/espacial sobre camadas oficiais
 *    - 'derivado': Resultante de combinação/operação aritmética entre outros indicadores oficiais
 * 3. Projeção e CRS Métrico: SIRGAS 2000 / UTM Zona 22S (EPSG:31982)
 */

export const TERRITORIAL_METRICS_GROUPS = [
  {
    id: 'divisao_territorial',
    title: '1. Divisão Territorial & Limites',
    iconName: 'map-pin',
    description: 'Dimensão territorial, perímetro urbano, divisão censitária e administrativa do município'
  },
  {
    id: 'sistema_viario',
    title: '2. Sistema Viário & Transporte',
    iconName: 'navigation',
    description: 'Extensão das malhas viárias, rodovias federais/estaduais, estradas municipais, ferrovias e pontes'
  },
  {
    id: 'hidrografia',
    title: '3. Hidrografia & Recursos Hídricos',
    iconName: 'droplet',
    description: 'Rede hidrográfica, curso principal do Rio Passo Fundo, bacias e sub-bacias'
  },
  {
    id: 'populacao',
    title: '4. População & Indicadores Econômicos',
    iconName: 'users',
    description: 'Demografia oficial Censo IBGE 2022, domicílios, densidade, estrutura etária e rendimento'
  }
];

export const TERRITORIAL_METRICS = [
  // =========================================================================
  // 1. DIVISÃO TERRITORIAL & LIMITES
  // =========================================================================
  {
    id: 'area_territorial_total',
    groupId: 'divisao_territorial',
    title: 'Área Territorial Municipal',
    value: 784.41,
    formattedValue: '784,41',
    unit: 'km²',
    subtitle: 'Área territorial total do Município de Passo Fundo',
    source: 'IBGE — Malha Municipal Oficial',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Área Territorial',
    calculationStatus: 'oficial',
    methodology: 'Valor cadastral oficial da malha de limites municipais do IBGE (Atributo AREA_KM2). Cálculo geométrico em UTM 22S: 784,17 km².',
    iconName: 'map',
    associatedLayerId: 'limite_territorial'
  },
  {
    id: 'area_urbana_plano_diretor',
    groupId: 'divisao_territorial',
    title: 'Área Urbana (Plano Diretor)',
    value: 86.60,
    formattedValue: '86,60',
    unit: 'km²',
    subtitle: '11,04% do território municipal total',
    source: 'SEPLAN — Perímetro Urbano / Plano Diretor',
    sourceAuthority: 'Secretaria Municipal de Planejamento (SEPLAN)',
    referenceYear: '2026',
    dataType: 'Área Urbana',
    calculationStatus: 'calculado',
    methodology: 'Cálculo geométrico exato em projeção métrica EPSG:31982 (UTM 22S) do polígono do Perímetro Urbano (86.602.418 m² / 1.000.000).',
    iconName: 'building-2',
    associatedLayerId: 'limite_plano_diretor'
  },
  {
    id: 'area_rural_estimada',
    groupId: 'divisao_territorial',
    title: 'Área Rural',
    value: 697.81,
    formattedValue: '697,81',
    unit: 'km²',
    subtitle: '88,96% do território municipal total',
    source: 'Derivada Territorial (SEPLAN / IBGE)',
    sourceAuthority: 'SEPLAN / IBGE',
    referenceYear: '2026',
    dataType: 'Área Rural',
    calculationStatus: 'derivado',
    methodology: 'Diferença aritmética entre a área municipal oficial e a área urbana do Plano Diretor: 784,41 km² - 86,60 km² = 697,81 km².',
    iconName: 'trees',
    associatedLayerId: null
  },
  {
    id: 'total_bairros_oficiais',
    groupId: 'divisao_territorial',
    title: 'Bairros Oficiais',
    value: 23,
    formattedValue: '23',
    unit: 'bairros',
    subtitle: 'Divisão político-administrativa urbana',
    source: 'Lei Municipal 4.133/2004 — Cadastro Técnico SEPLAN',
    sourceAuthority: 'Câmara Municipal e SEPLAN Passo Fundo',
    referenceYear: '2004',
    dataType: 'Unidades Administrativas',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 23 feições poligonais de bairros municipais oficializados pela Lei 4.133/2004.',
    iconName: 'home',
    associatedLayerId: 'bairros'
  },
  {
    id: 'total_distritos_municipais',
    groupId: 'divisao_territorial',
    title: 'Distritos Municipais',
    value: 7,
    formattedValue: '7',
    unit: 'distritos',
    subtitle: 'Passo Fundo (Sede), São Roque, Bom Recreio, Bela Vista, Capinzal, Independência e Pulador',
    source: 'SEPLAN — Divisão Distrital Municipal',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Divisão Regional',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 7 sedes distritais georreferenciadas na base cadastral municipal.',
    iconName: 'flag',
    associatedLayerId: 'distritos'
  },
  {
    id: 'total_setores_censitarios',
    groupId: 'divisao_territorial',
    title: 'Setores Censitários',
    value: 321,
    formattedValue: '321',
    unit: 'setores',
    subtitle: 'Unidades territoriais de coleta estatística do Censo 2022',
    source: 'IBGE — Censo Demográfico 2022',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Malha Censitária',
    calculationStatus: 'oficial',
    methodology: 'Contagem de feições poligonais da malha oficial de setores censitários de Passo Fundo (código do município 4314100). Malha oficial consolidada do Censo Demográfico 2022 (321 setores).',
    iconName: 'grid',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'total_municipios_limitrofes',
    groupId: 'divisao_territorial',
    title: 'Municípios Limítrofes',
    value: 7,
    formattedValue: '7',
    unit: 'municípios',
    subtitle: 'Confrontantes: Marau, Coxilha, Pontão, Carazinho, Ernestina, Mato Castelhano e Santo Antônio do Planalto',
    source: 'IBGE — Malha de Municípios do Rio Grande do Sul',
    sourceAuthority: 'IBGE',
    referenceYear: '2024',
    dataType: 'Limites Geográficos',
    calculationStatus: 'oficial',
    methodology: 'Contagem dos municípios limítrofes adjacentes ao território de Passo Fundo mapeados na camada confrontante.',
    iconName: 'compass',
    associatedLayerId: 'municipios_rs'
  },

  // =========================================================================
  // 2. SISTEMA VIÁRIO & TRANSPORTE
  // =========================================================================
  {
    id: 'extensao_total_malha_viaria',
    groupId: 'sistema_viario',
    title: 'Extensão Total da Malha Viária',
    value: 1904.05,
    formattedValue: '1.904,05',
    unit: 'km',
    subtitle: 'Soma integrada de todas as vias mapeadas no município',
    source: 'Soma Integrada Multicritério (SEPLAN / DAER / DNIT)',
    sourceAuthority: 'SEPLAN, DAER/RS e DNIT',
    referenceYear: '2026',
    dataType: 'Infraestrutura Viária',
    calculationStatus: 'derivado',
    methodology: 'Soma integrada das extensões das categorias viárias: vias urbanas (1.501,61 km) + estradas municipais (285,29 km) + rodovias estaduais (66,86 km) + rodovias federais (50,29 km).',
    iconName: 'network',
    associatedLayerId: 'malha_viaria'
  },
  {
    id: 'extensao_malha_urbana',
    groupId: 'sistema_viario',
    title: 'Malha Viária Urbana',
    value: 1501.61,
    formattedValue: '1.501,61',
    unit: 'km',
    subtitle: '11.595 segmentos viários urbanos cadastrados',
    source: 'SEPLAN / Cadastro Técnico Municipal',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Vias Urbanas',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em projeção UTM 22S (EPSG:31982) de 11.595 geometrias LineString/MultiLineString da malha viária urbana.',
    iconName: 'milestone',
    associatedLayerId: 'malha_viaria'
  },
  {
    id: 'extensao_estradas_municipais',
    groupId: 'sistema_viario',
    title: 'Estradas Municipais / Rurais',
    value: 285.29,
    formattedValue: '285,29',
    unit: 'km',
    subtitle: '164 trechos de vias rurais e acessos vicinais',
    source: 'SEPLAN — Malha de Estradas Municipais',
    sourceAuthority: 'Secretaria Municipal de Planejamento e Obras',
    referenceYear: '2026',
    dataType: 'Vias Rurais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 164 trechos da camada de estradas municipais.',
    iconName: 'route',
    associatedLayerId: 'estradas_municipais'
  },
  {
    id: 'extensao_rodovias_estaduais',
    groupId: 'sistema_viario',
    title: 'Rodovias Estaduais (RS)',
    value: 66.86,
    formattedValue: '66,86',
    unit: 'km',
    subtitle: 'RS-153, RS-324 e RS-135 (52 trechos no território)',
    source: 'DAER/RS — Departamento Autônomo de Estradas de Rodagem',
    sourceAuthority: 'DAER/RS',
    referenceYear: '2024',
    dataType: 'Rodovias Estaduais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 52 segmentos estaduais no perímetro municipal.',
    iconName: 'navigation-2',
    associatedLayerId: 'rodovia_estadual'
  },
  {
    id: 'extensao_rodovias_federais',
    groupId: 'sistema_viario',
    title: 'Rodovias Federais (BR)',
    value: 50.29,
    formattedValue: '50,29',
    unit: 'km',
    subtitle: 'BR-285 e BR-153 (31 trechos no território municipal)',
    source: 'DNIT — Departamento Nacional de Infraestrutura de Transportes',
    sourceAuthority: 'DNIT',
    referenceYear: '2024',
    dataType: 'Rodovias Federais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 31 segmentos federais no perímetro municipal.',
    iconName: 'signpost',
    associatedLayerId: 'rodovia_federal'
  },
  {
    id: 'extensao_malha_ferroviaria',
    groupId: 'sistema_viario',
    title: 'Malha Ferroviária',
    value: 55.29,
    formattedValue: '55,29',
    unit: 'km',
    subtitle: '3 trechos ferroviários estratégicos de transporte de cargas',
    source: 'ANTT / Rumo Logística',
    sourceAuthority: 'Agência Nacional de Transportes Terrestres (ANTT)',
    referenceYear: '2024',
    dataType: 'Ferrovia',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 3 segmentos ferroviários no território municipal.',
    iconName: 'train',
    associatedLayerId: 'ferrovia'
  },
  {
    id: 'total_pontes_passagens',
    groupId: 'sistema_viario',
    title: 'Pontes e Passagens Hídricas',
    value: 11,
    formattedValue: '11',
    unit: 'unidades',
    subtitle: 'Pontes estruturais sobre cursos d’água cadastrados',
    source: 'SEPLAN — Infraestrutura e Obras de Arte Especiais',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Obras de Arte Especiais',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 11 feições estruturais georreferenciadas na camada oficial de pontes.',
    iconName: 'milestone',
    associatedLayerId: 'pontes'
  },

  // =========================================================================
  // 3. HIDROGRAFIA & RECURSOS HÍDRICOS
  // =========================================================================
  {
    id: 'extensao_rede_hidrografica',
    groupId: 'hidrografia',
    title: 'Extensão da Rede Hidrográfica',
    value: 1674.74,
    formattedValue: '1.674,74',
    unit: 'km',
    subtitle: '3.682 trechos fluviais (rios e arroios municipais)',
    source: 'Prefeitura Municipal / Secretaria de Meio Ambiente',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Rede Hidrográfica',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em projeção UTM 22S (EPSG:31982) das 3.682 feições fluviais da malha hídrica.',
    iconName: 'droplets',
    associatedLayerId: 'malha_hidrica'
  },
  {
    id: 'extensao_rio_passo_fundo',
    groupId: 'hidrografia',
    title: 'Rio Passo Fundo (Curso Principal)',
    value: 19.76,
    formattedValue: '19,76',
    unit: 'km',
    subtitle: '21 segmentos do curso d’água principal do município',
    source: 'Prefeitura Municipal de Passo Fundo',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Curso Hídrico Principal',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 21 segmentos contínuos do leito do Rio Passo Fundo.',
    iconName: 'waves',
    associatedLayerId: 'rio_passo_fundo'
  },
  {
    id: 'total_trechos_fluviais',
    groupId: 'hidrografia',
    title: 'Cursos d’Água / Trechos Fluviais',
    value: 3682,
    formattedValue: '3.682',
    unit: 'cursos d’água',
    subtitle: 'Segmentos fluviais hierarquizados na hidrografia municipal',
    source: 'Prefeitura Municipal de Passo Fundo',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Hidrografia Geral',
    calculationStatus: 'calculado',
    methodology: 'Contagem total de feições vetoriais ativas na camada Malha Hídrica.',
    iconName: 'git-branch',
    associatedLayerId: 'malha_hidrica'
  },
  {
    id: 'total_bacias_hidrograficas',
    groupId: 'hidrografia',
    title: 'Bacias e Sub-bacias Hidrográficas',
    value: 6,
    formattedValue: '6',
    unit: 'divisores/bacias',
    subtitle: 'Macrozonas e divisores de drenagem hídrica municipal',
    source: 'SEPLAN — Bacias Hidrográficas de Passo Fundo',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Bacias Hidrográficas',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 6 feições cartográficas de divisores e unidades de bacias municipais.',
    iconName: 'pie-chart',
    associatedLayerId: 'bacias_hidrograficas'
  },

  // =========================================================================
  // 4. POPULAÇÃO & INDICADORES ECONÔMICOS
  // =========================================================================
  {
    id: 'populacao_total_censo_2022',
    groupId: 'populacao',
    title: 'População Residente Total',
    value: 206215,
    formattedValue: '206.215',
    unit: 'habitantes',
    subtitle: 'População oficial do Censo Demográfico IBGE 2022',
    source: 'IBGE — Censo Demográfico 2022 (Variável V0001)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Demografia Oficial',
    calculationStatus: 'oficial',
    methodology: 'População apurada no Censo Demográfico 2022, confirmada pela soma da variável V0001 nos 321 setores censitários municipais.',
    iconName: 'users',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'total_domicilios_censo_2022',
    groupId: 'populacao',
    title: 'Total de Domicílios Particulares',
    value: 95786,
    formattedValue: '95.786',
    unit: 'domicílios',
    subtitle: 'Domicílios particulares permanentes ocupados (Censo 2022)',
    source: 'IBGE — Censo Demográfico 2022 (Variável V0002)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Habitação e Domicílios',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável V0002 (domicílios particulares permanentes ocupados) nos 321 setores censitários municipais.',
    iconName: 'building',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'densidade_demografica_media',
    groupId: 'populacao',
    title: 'Densidade Demográfica Média',
    value: 262.9,
    formattedValue: '262,9',
    unit: 'hab/km²',
    subtitle: 'Relação entre população total e área territorial municipal',
    source: 'Cálculo Oficial Derivado (IBGE 2022)',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Densidade Demográfica',
    calculationStatus: 'calculado',
    methodology: 'Divisão direta da população residente total pela área territorial oficial do município: 206.215 hab / 784,41 km² = 262,89 hab/km².',
    iconName: 'maximize-2',
    associatedLayerId: 'censo_densidade_2022'
  },
  {
    id: 'rendimento_medio_domiciliar',
    groupId: 'populacao',
    title: 'Rendimento Médio Mensal Domiciliar',
    value: 3895.50,
    formattedValue: 'R$ 3.895,50',
    unit: 'por domicílio',
    subtitle: 'Média setorial apurada pelo Censo 2022 em 307 setores válidos',
    source: 'IBGE — Censo 2022 (Variável V06004 / Redus)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Indicador Socioeconômico',
    calculationStatus: 'calculado',
    methodology: 'Média aritmética do rendimento nominal médio mensal domiciliar apurado nos 307 setores censitários municipais com dados válidos.',
    iconName: 'wallet',
    associatedLayerId: 'censo_renda_vulnerabilidade'
  },
  {
    id: 'faixa_etaria_adultos',
    groupId: 'populacao',
    title: 'População Adulta (20 a 59 anos)',
    value: 119496,
    formattedValue: '119.496',
    unit: 'habitantes',
    subtitle: '57,95% da população residente do município',
    source: 'IBGE — Censo 2022 (Variável cn22_pop03_20a59_tot_1)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial cn22_pop03_20a59_tot_1 nos setores censitários do Censo 2022.',
    iconName: 'user-check',
    associatedLayerId: 'censo_pop_20a59'
  },
  {
    id: 'faixa_etaria_idosos',
    groupId: 'populacao',
    title: 'População Idosa (60 anos ou mais)',
    value: 35944,
    formattedValue: '35.944',
    unit: 'habitantes',
    subtitle: '17,43% da população residente municipal (Grupo Prioritário)',
    source: 'IBGE — Censo 2022 (Variável cn22_pop03_m60_tot_1)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial cn22_pop03_m60_tot_1 nos setores censitários do Censo 2022.',
    iconName: 'heart',
    associatedLayerId: 'censo_pop_m60'
  },
  {
    id: 'faixa_etaria_jovens_criancas',
    groupId: 'populacao',
    title: 'Crianças e Jovens (0 a 19 anos)',
    value: 50775,
    formattedValue: '50.775',
    unit: 'habitantes',
    subtitle: '24,62% da população (0-4: 12.482; 5-9: 13.200; 10-14: 12.560; 15-19: 12.533)',
    source: 'IBGE — Censo Demográfico 2022',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'derivado',
    methodology: 'Soma das 4 faixas etárias censitárias infantojuvenis oficiais: 12.482 + 13.200 + 12.560 + 12.533 = 50.775 habitantes.',
    iconName: 'baby',
    associatedLayerId: 'censo_pop_0a4'
  },
  {
    id: 'razao_sexo_censo_2022',
    groupId: 'populacao',
    title: 'Razão de Sexo (Homens / 100 Mulheres)',
    value: 90.04,
    formattedValue: '90,04',
    unit: 'H / 100 M',
    subtitle: '47,38% homens vs 52,62% mulheres (excedente de 10.776 mulheres)',
    source: 'IBGE — Censo Demográfico 2022 (Variáveis V01007 e V01008)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Demografia Oficial',
    calculationStatus: 'oficial',
    methodology: 'Razão matemática oficial entre a população masculina (97.467) e feminina (108.243): (97.467 / 108.243) * 100 = 90,04 homens para cada 100 mulheres.',
    iconName: 'users',
    associatedLayerId: null
  },
  {
    id: 'indice_envelhecimento_censo_2022',
    groupId: 'populacao',
    title: 'Índice de Envelhecimento',
    value: 92.45,
    formattedValue: '92,45',
    unit: 'idosos / 100 jovens',
    subtitle: '35.356 idosos (60+ anos) para 38.242 crianças/jovens (0 a 14 anos)',
    source: 'IBGE — Censo Demográfico 2022',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'oficial',
    methodology: 'Relação entre idosos de 60 anos ou mais (35.356) e jovens de 0 a 14 anos (38.242): (35.356 / 38.242) * 100 = 92,45%.',
    iconName: 'trending-up',
    associatedLayerId: 'censo_pop_m60'
  },
  {
    id: 'populacao_feminina_censo_2022',
    groupId: 'populacao',
    title: 'População Feminina Residente',
    value: 108243,
    formattedValue: '108.243',
    unit: 'mulheres',
    subtitle: '52,62% da população residente do município (maioria demográfica)',
    source: 'IBGE — Censo Demográfico 2022 (Variável V01008)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Demografia Oficial',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial V01008 apurada nos setores censitários com domicílios habitados.',
    iconName: 'user-check',
    associatedLayerId: null
  },
  {
    id: 'populacao_masculina_censo_2022',
    groupId: 'populacao',
    title: 'População Masculina Residente',
    value: 97467,
    formattedValue: '97.467',
    unit: 'homens',
    subtitle: '47,38% da população residente do município',
    source: 'IBGE — Censo Demográfico 2022 (Variável V01007)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Demografia Oficial',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial V01007 apurada nos setores censitários com domicílios habitados.',
    iconName: 'user',
    associatedLayerId: null
  },
  {
    id: 'bairro_maior_envelhecimento',
    groupId: 'populacao',
    title: 'Bairro com Maior Envelhecimento',
    value: 205.49,
    formattedValue: '205,5%',
    unit: 'Centro / Vergueiro',
    subtitle: '5.655 idosos para 2.752 jovens (205,5 idosos para cada 100 jovens)',
    source: 'IBGE — Censo Demográfico 2022 / Agregação Setores SEPLAN',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Disparidade Territorial',
    calculationStatus: 'calculado',
    methodology: 'Cruzamento espacial exato dos 321 setores censitários do Censo 2022 com o perímetro do Setor 01 (Centro e Vila Vergueiro).',
    iconName: 'activity',
    associatedLayerId: 'bairros'
  },
  {
    id: 'bairro_menor_envelhecimento',
    groupId: 'populacao',
    title: 'Bairro Mais Jovem / Menor Envelhecimento',
    value: 40.97,
    formattedValue: '41,0%',
    unit: 'José Alexandre Zachia',
    subtitle: '1.091 jovens (0-14) para 447 idosos (quase 3 jovens por idoso)',
    source: 'IBGE — Censo Demográfico 2022 / Agregação Setores SEPLAN',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Disparidade Territorial',
    calculationStatus: 'calculado',
    methodology: 'Cruzamento espacial exato dos setores censitários do Censo 2022 com o Setor 16 (José Alexandre Zachia), registrando 40,97 idosos para cada 100 jovens.',
    iconName: 'baby',
    associatedLayerId: 'bairros'
  },
  {
    id: 'bairro_maior_presenca_feminina',
    groupId: 'populacao',
    title: 'Maior Predomínio Feminino por Bairro',
    value: 76.72,
    formattedValue: '76,7 H / 100 M',
    unit: 'Centro / Vergueiro',
    subtitle: '56,59% mulheres (15.238) vs 43,41% homens (11.691)',
    source: 'IBGE — Censo Demográfico 2022 / Agregação Setores SEPLAN',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Disparidade Territorial',
    calculationStatus: 'calculado',
    methodology: 'Razão de sexo calculada no Setor 01 (76,72 homens por 100 mulheres), evidenciando a concentração da longevidade feminina nas áreas centrais estruturadas.',
    iconName: 'users',
    associatedLayerId: 'bairros'
  },
  {
    id: 'taxa_alfabetizacao_passo_fundo',
    groupId: 'populacao',
    title: 'Taxa de Alfabetização Municipal',
    value: 97.59,
    formattedValue: '97,59%',
    unit: 'Passo Fundo',
    subtitle: '163.338 pessoas alfabetizadas de 167.376 residentes de 15+ anos',
    source: 'IBGE — Censo Demográfico 2022 (Variável V00900 / Universo 15+)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Educação e Alfabetização',
    calculationStatus: 'oficial',
    methodology: 'Taxa calculada sobre o universo censitário de 15 anos ou mais apurado nos 321 setores censitários (163.338 alfabetizados de 167.376 pessoas).',
    iconName: 'book-open',
    associatedLayerId: 'censo_alfabetizacao_2022'
  },
  {
    id: 'taxa_analfabetismo_passo_fundo',
    groupId: 'populacao',
    title: 'Taxa de Não Alfabetização Municipal',
    value: 2.41,
    formattedValue: '2,41%',
    unit: 'Passo Fundo',
    subtitle: '4.038 pessoas não alfabetizadas no universo de 15 anos ou mais',
    source: 'IBGE — Censo Demográfico 2022 (Variável V00901)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Educação e Alfabetização',
    calculationStatus: 'oficial',
    methodology: 'Contingente e proporção de moradores com 15 anos ou mais que não sabem ler e escrever apurados pelo Censo IBGE 2022.',
    iconName: 'alert-circle',
    associatedLayerId: 'censo_alfabetizacao_2022'
  },
  {
    id: 'bairro_maior_alfabetizacao',
    groupId: 'populacao',
    title: 'Bairro c/ Maior Taxa de Alfabetização',
    value: 99.64,
    formattedValue: '99,64%',
    unit: 'Centro / Vergueiro',
    subtitle: '24.061 alfabetizados para apenas 86 não alfabetizados (15+ anos)',
    source: 'IBGE — Censo 2022 / Agregação Territorial SEPLAN',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Disparidade Territorial',
    calculationStatus: 'calculado',
    methodology: 'Agregação territorial segundo recortes de planejamento da SEPLAN. Setor 01 (Centro e Vila Vergueiro) registrou a maior taxa municipal (99,64%).',
    iconName: 'award',
    associatedLayerId: 'censo_alfabetizacao_2022'
  },
  {
    id: 'bairro_menor_taxa_alfabetizacao',
    groupId: 'populacao',
    title: 'Menor Taxa de Alfabetização entre Regiões',
    value: 94.36,
    formattedValue: '94,36%',
    unit: 'José Alexandre Zachia',
    subtitle: '2.224 alfabetizados e 133 não alfabetizados de 2.357 residentes (15+ anos)',
    source: 'IBGE — Censo 2022 / Agregação Territorial SEPLAN',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Disparidade Territorial',
    calculationStatus: 'calculado',
    methodology: 'Agregação territorial descritiva segundo recortes de planejamento da SEPLAN. Setor 16 (José Alexandre Zachia) registrou 94,36% de alfabetização (5,64% de não alfabetizados).',
    iconName: 'info',
    associatedLayerId: 'censo_alfabetizacao_2022'
  },
  {
    id: 'pib_per_capita_passo_fundo',
    groupId: 'populacao',
    title: 'PIB Per Capita Municipal',
    value: 68227.53,
    formattedValue: 'R$ 68.227,53',
    unit: 'por habitante',
    subtitle: 'Rendimento econômico anual por morador (Ano base 2023)',
    source: 'IBGE — PIB dos Municípios 2023',
    sourceUrl: 'https://cidades.ibge.gov.br/brasil/rs/passo-fundo/pesquisa/38/47000',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE) e DEE/SPGG-RS',
    referenceYear: '2023',
    dataType: 'Indicador Macroeconômico',
    calculationStatus: 'oficial',
    methodology: 'Razão direta entre o Produto Interno Bruto a preços correntes (R$ 14.069.540.000) e a população residente do município (206.215 habitantes, Censo Demográfico 2022).',
    iconName: 'trending-up',
    associatedLayerId: null
  },
  {
    id: 'pib_total_passo_fundo',
    groupId: 'populacao',
    title: 'Produto Interno Bruto (PIB Total)',
    value: 14069540000,
    formattedValue: 'R$ 14,07 bi',
    unit: 'R$ correntes',
    subtitle: 'R$ 14.069.540.000 apurados no Sistema de Contas Regionais 2023',
    source: 'IBGE — SIDRA Tabela 5938',
    sourceUrl: 'https://sidra.ibge.gov.br/tabela/5938',
    sourceAuthority: 'IBGE / Sistema de Contas Nacionais',
    referenceYear: '2023',
    dataType: 'Produção Econômica',
    calculationStatus: 'oficial',
    methodology: 'Soma dos valores adicionados brutos a preços correntes da agropecuária, indústria, serviços e administração pública, acrescidos dos impostos sobre produtos líquidos de subsídios.',
    iconName: 'landmark',
    associatedLayerId: null
  },
  {
    id: 'ranking_pib_rs',
    groupId: 'populacao',
    title: 'Posição no PIB do Rio Grande do Sul',
    value: 6,
    formattedValue: '6ª Posição',
    unit: 'entre 497 municípios',
    subtitle: 'Passo Fundo consolidada entre as 6 maiores economias do RS',
    source: 'IBGE / DEE-RS — Contas Regionais',
    sourceUrl: 'https://cidades.ibge.gov.br/brasil/rs/passo-fundo/pesquisa/38/47000',
    sourceAuthority: 'IBGE e Governo do Estado do RS',
    referenceYear: '2023',
    dataType: 'Classificação Econômica',
    calculationStatus: 'oficial',
    methodology: 'Ordenação decrescente do PIB municipal entre todos os 497 municípios do Rio Grande do Sul. Passo Fundo figura na 6ª posição estadual.',
    iconName: 'award',
    associatedLayerId: null
  }
];
