/**
 * WebGIS SEPLAN Passo Fundo - Diagnósticos Territoriais
 * Catálogo Estruturado de Métricas e Indicadores Territoriais Oficiais
 * 
 * Regras Fundamentais de Governança dos Dados:
 * 1. Dados 100% reais, auditados sobre o acervo geoespacial do município.
 * 2. Classificação rigorosa de calculationStatus:
 *    - 'oficial': Diretamente fornecido pelo órgão oficial (IBGE, Lei Municipal, etc.)
 *    - 'calculado': Obtido por processamento geométrico/espacial sobre camadas oficiais
 *    - 'derivado': Resultante de combinação/operação aritmética entre outros indicadores oficiais
 * 3. Projeção e CRS Métrico: SIRGAS 2000 / UTM Zona 22S (EPSG:31982)
 */

export const TERRITORIAL_METRICS_GROUPS = [
  {
    id: 'divisao_territorial',
    title: '1. Divisão Territorial & Limites',
    iconName: 'map-pin',
    description: 'Dimensão territorial, perímetro urbano, divisão censitária e administrativa do município'
  },
  {
    id: 'sistema_viario',
    title: '2. Sistema Viário & Transporte',
    iconName: 'navigation',
    description: 'Extensão das malhas viárias, rodovias federais/estaduais, estradas municipais, ferrovias e pontes'
  },
  {
    id: 'hidrografia',
    title: '3. Hidrografia & Recursos Hídricos',
    iconName: 'droplet',
    description: 'Rede hidrográfica, curso principal do Rio Passo Fundo, bacias e sub-bacias'
  },
  {
    id: 'populacao',
    title: '4. População & Indicadores Econômicos',
    iconName: 'users',
    description: 'Demografia oficial Censo IBGE 2022, domicílios, densidade, estrutura etária e rendimento'
  }
];

export const TERRITORIAL_METRICS = [
  // =========================================================================
  // 1. DIVISÃO TERRITORIAL & LIMITES
  // =========================================================================
  {
    id: 'area_territorial_total',
    groupId: 'divisao_territorial',
    title: 'Área Territorial Municipal',
    value: 784.41,
    formattedValue: '784,41',
    unit: 'km²',
    subtitle: 'Área territorial total do Município de Passo Fundo',
    source: 'IBGE — Malha Municipal Oficial',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Área Territorial',
    calculationStatus: 'oficial',
    methodology: 'Valor cadastral oficial da malha de limites municipais do IBGE (Atributo AREA_KM2). Cálculo geométrico em UTM 22S: 784,17 km².',
    iconName: 'map',
    associatedLayerId: 'limite_territorial'
  },
  {
    id: 'area_urbana_plano_diretor',
    groupId: 'divisao_territorial',
    title: 'Área Urbana (Plano Diretor)',
    value: 86.60,
    formattedValue: '86,60',
    unit: 'km²',
    subtitle: '11,04% do território municipal total',
    source: 'SEPLAN — Perímetro Urbano / Plano Diretor',
    sourceAuthority: 'Secretaria Municipal de Planejamento (SEPLAN)',
    referenceYear: '2026',
    dataType: 'Área Urbana',
    calculationStatus: 'calculado',
    methodology: 'Cálculo geométrico exato em projeção métrica EPSG:31982 (UTM 22S) do polígono do Perímetro Urbano (86.602.418 m² / 1.000.000).',
    iconName: 'building-2',
    associatedLayerId: 'limite_plano_diretor'
  },
  {
    id: 'area_rural_estimada',
    groupId: 'divisao_territorial',
    title: 'Área Rural',
    value: 697.81,
    formattedValue: '697,81',
    unit: 'km²',
    subtitle: '88,96% do território municipal total',
    source: 'Derivada Territorial (SEPLAN / IBGE)',
    sourceAuthority: 'SEPLAN / IBGE',
    referenceYear: '2026',
    dataType: 'Área Rural',
    calculationStatus: 'derivado',
    methodology: 'Diferença aritmética entre a área municipal oficial e a área urbana do Plano Diretor: 784,41 km² - 86,60 km² = 697,81 km².',
    iconName: 'trees',
    associatedLayerId: null
  },
  {
    id: 'total_bairros_oficiais',
    groupId: 'divisao_territorial',
    title: 'Bairros Oficiais',
    value: 23,
    formattedValue: '23',
    unit: 'bairros',
    subtitle: 'Divisão político-administrativa urbana',
    source: 'Lei Municipal 4.133/2004 — Cadastro Técnico SEPLAN',
    sourceAuthority: 'Câmara Municipal e SEPLAN Passo Fundo',
    referenceYear: '2004',
    dataType: 'Unidades Administrativas',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 23 feições poligonais de bairros municipais oficializados pela Lei 4.133/2004.',
    iconName: 'home',
    associatedLayerId: 'bairros'
  },
  {
    id: 'total_distritos_municipais',
    groupId: 'divisao_territorial',
    title: 'Distritos Municipais',
    value: 7,
    formattedValue: '7',
    unit: 'distritos',
    subtitle: 'Passo Fundo (Sede), São Roque, Bom Recreio, Bela Vista, Capinzal, Independência e Pulador',
    source: 'SEPLAN — Divisão Distrital Municipal',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Divisão Regional',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 7 sedes distritais georreferenciadas na base cadastral municipal.',
    iconName: 'flag',
    associatedLayerId: 'distritos'
  },
  {
    id: 'total_setores_censitarios',
    groupId: 'divisao_territorial',
    title: 'Setores Censitários',
    value: 312,
    formattedValue: '312',
    unit: 'setores',
    subtitle: 'Unidades territoriais de coleta estatística do Censo 2022',
    source: 'IBGE — Censo Demográfico 2022',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Malha Censitária',
    calculationStatus: 'oficial',
    methodology: 'Contagem de feições poligonais da malha oficial de setores censitários de Passo Fundo (código do município 4314100).',
    iconName: 'grid',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'total_municipios_limitrofes',
    groupId: 'divisao_territorial',
    title: 'Municípios Limítrofes',
    value: 7,
    formattedValue: '7',
    unit: 'municípios',
    subtitle: 'Confrontantes: Marau, Coxilha, Pontão, Carazinho, Ernestina, Mato Castelhano e Santo Antônio do Planalto',
    source: 'IBGE — Malha de Municípios do Rio Grande do Sul',
    sourceAuthority: 'IBGE',
    referenceYear: '2024',
    dataType: 'Limites Geográficos',
    calculationStatus: 'oficial',
    methodology: 'Contagem dos municípios limítrofes adjacentes ao território de Passo Fundo mapeados na camada confrontante.',
    iconName: 'compass',
    associatedLayerId: 'municipios_rs'
  },

  // =========================================================================
  // 2. SISTEMA VIÁRIO & TRANSPORTE
  // =========================================================================
  {
    id: 'extensao_total_malha_viaria',
    groupId: 'sistema_viario',
    title: 'Extensão Total da Malha Viária',
    value: 1904.05,
    formattedValue: '1.904,05',
    unit: 'km',
    subtitle: 'Soma integrada de todas as vias mapeadas no município',
    source: 'Soma Integrada Multicritério (SEPLAN / DAER / DNIT)',
    sourceAuthority: 'SEPLAN, DAER/RS e DNIT',
    referenceYear: '2026',
    dataType: 'Infraestrutura Viária',
    calculationStatus: 'derivado',
    methodology: 'Soma integrada das extensões das categorias viárias: vias urbanas (1.501,61 km) + estradas municipais (285,29 km) + rodovias estaduais (66,86 km) + rodovias federais (50,29 km).',
    iconName: 'network',
    associatedLayerId: 'malha_viaria'
  },
  {
    id: 'extensao_malha_urbana',
    groupId: 'sistema_viario',
    title: 'Malha Viária Urbana',
    value: 1501.61,
    formattedValue: '1.501,61',
    unit: 'km',
    subtitle: '11.595 segmentos viários urbanos cadastrados',
    source: 'SEPLAN / Cadastro Técnico Municipal',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Vias Urbanas',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em projeção UTM 22S (EPSG:31982) de 11.595 geometrias LineString/MultiLineString da malha viária urbana.',
    iconName: 'milestone',
    associatedLayerId: 'malha_viaria'
  },
  {
    id: 'extensao_estradas_municipais',
    groupId: 'sistema_viario',
    title: 'Estradas Municipais / Rurais',
    value: 285.29,
    formattedValue: '285,29',
    unit: 'km',
    subtitle: '164 trechos de vias rurais e acessos vicinais',
    source: 'SEPLAN — Malha de Estradas Municipais',
    sourceAuthority: 'Secretaria Municipal de Planejamento e Obras',
    referenceYear: '2026',
    dataType: 'Vias Rurais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 164 trechos da camada de estradas municipais.',
    iconName: 'route',
    associatedLayerId: 'estradas_municipais'
  },
  {
    id: 'extensao_rodovias_estaduais',
    groupId: 'sistema_viario',
    title: 'Rodovias Estaduais (RS)',
    value: 66.86,
    formattedValue: '66,86',
    unit: 'km',
    subtitle: 'RS-153, RS-324 e RS-135 (52 trechos no território)',
    source: 'DAER/RS — Departamento Autônomo de Estradas de Rodagem',
    sourceAuthority: 'DAER/RS',
    referenceYear: '2024',
    dataType: 'Rodovias Estaduais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 52 segmentos estaduais no perímetro municipal.',
    iconName: 'navigation-2',
    associatedLayerId: 'rodovia_estadual'
  },
  {
    id: 'extensao_rodovias_federais',
    groupId: 'sistema_viario',
    title: 'Rodovias Federais (BR)',
    value: 50.29,
    formattedValue: '50,29',
    unit: 'km',
    subtitle: 'BR-285 e BR-153 (31 trechos no território municipal)',
    source: 'DNIT — Departamento Nacional de Infraestrutura de Transportes',
    sourceAuthority: 'DNIT',
    referenceYear: '2024',
    dataType: 'Rodovias Federais',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 31 segmentos federais no perímetro municipal.',
    iconName: 'signpost',
    associatedLayerId: 'rodovia_federal'
  },
  {
    id: 'extensao_malha_ferroviaria',
    groupId: 'sistema_viario',
    title: 'Malha Ferroviária',
    value: 55.29,
    formattedValue: '55,29',
    unit: 'km',
    subtitle: '3 trechos ferroviários estratégicos de transporte de cargas',
    source: 'ANTT / Rumo Logística',
    sourceAuthority: 'Agência Nacional de Transportes Terrestres (ANTT)',
    referenceYear: '2024',
    dataType: 'Ferrovia',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 3 segmentos ferroviários no território municipal.',
    iconName: 'train',
    associatedLayerId: 'ferrovia'
  },
  {
    id: 'total_pontes_passagens',
    groupId: 'sistema_viario',
    title: 'Pontes e Passagens Hídricas',
    value: 11,
    formattedValue: '11',
    unit: 'unidades',
    subtitle: 'Pontes estruturais sobre cursos d’água cadastrados',
    source: 'SEPLAN — Infraestrutura e Obras de Arte Especiais',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Obras de Arte Especiais',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 11 feições estruturais georreferenciadas na camada oficial de pontes.',
    iconName: 'milestone',
    associatedLayerId: 'pontes'
  },

  // =========================================================================
  // 3. HIDROGRAFIA & RECURSOS HÍDRICOS
  // =========================================================================
  {
    id: 'extensao_rede_hidrografica',
    groupId: 'hidrografia',
    title: 'Extensão da Rede Hidrográfica',
    value: 1674.74,
    formattedValue: '1.674,74',
    unit: 'km',
    subtitle: '3.682 trechos fluviais (rios e arroios municipais)',
    source: 'Prefeitura Municipal / Secretaria de Meio Ambiente',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Rede Hidrográfica',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em projeção UTM 22S (EPSG:31982) das 3.682 feições fluviais da malha hídrica.',
    iconName: 'droplets',
    associatedLayerId: 'malha_hidrica'
  },
  {
    id: 'extensao_rio_passo_fundo',
    groupId: 'hidrografia',
    title: 'Rio Passo Fundo (Curso Principal)',
    value: 19.76,
    formattedValue: '19,76',
    unit: 'km',
    subtitle: '21 segmentos do curso d’água principal do município',
    source: 'Prefeitura Municipal de Passo Fundo',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Curso Hídrico Principal',
    calculationStatus: 'calculado',
    methodology: 'Somatório métrico do comprimento euclidiano em UTM 22S (EPSG:31982) dos 21 segmentos contínuos do leito do Rio Passo Fundo.',
    iconName: 'waves',
    associatedLayerId: 'rio_passo_fundo'
  },
  {
    id: 'total_trechos_fluviais',
    groupId: 'hidrografia',
    title: 'Cursos d’Água / Trechos Fluviais',
    value: 3682,
    formattedValue: '3.682',
    unit: 'cursos d’água',
    subtitle: 'Segmentos fluviais hierarquizados na hidrografia municipal',
    source: 'Prefeitura Municipal de Passo Fundo',
    sourceAuthority: 'Prefeitura de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Hidrografia Geral',
    calculationStatus: 'calculado',
    methodology: 'Contagem total de feições vetoriais ativas na camada Malha Hídrica.',
    iconName: 'git-branch',
    associatedLayerId: 'malha_hidrica'
  },
  {
    id: 'total_bacias_hidrograficas',
    groupId: 'hidrografia',
    title: 'Bacias e Sub-bacias Hidrográficas',
    value: 6,
    formattedValue: '6',
    unit: 'divisores/bacias',
    subtitle: 'Macrozonas e divisores de drenagem hídrica municipal',
    source: 'SEPLAN — Bacias Hidrográficas de Passo Fundo',
    sourceAuthority: 'Prefeitura Municipal de Passo Fundo',
    referenceYear: '2026',
    dataType: 'Bacias Hidrográficas',
    calculationStatus: 'oficial',
    methodology: 'Contagem das 6 feições cartográficas de divisores e unidades de bacias municipais.',
    iconName: 'pie-chart',
    associatedLayerId: 'bacias_hidrograficas'
  },

  // =========================================================================
  // 4. POPULAÇÃO & INDICADORES ECONÔMICOS
  // =========================================================================
  {
    id: 'populacao_total_censo_2022',
    groupId: 'populacao',
    title: 'População Residente Total',
    value: 206215,
    formattedValue: '206.215',
    unit: 'habitantes',
    subtitle: 'População oficial do Censo Demográfico IBGE 2022',
    source: 'IBGE — Censo Demográfico 2022 (Variável V0001)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Demografia Oficial',
    calculationStatus: 'oficial',
    methodology: 'População apurada no Censo Demográfico 2022, confirmada pela soma da variável V0001 nos 312 setores censitários municipais.',
    iconName: 'users',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'total_domicilios_censo_2022',
    groupId: 'populacao',
    title: 'Total de Domicílios Particulares',
    value: 95786,
    formattedValue: '95.786',
    unit: 'domicílios',
    subtitle: 'Domicílios particulares permanentes ocupados (Censo 2022)',
    source: 'IBGE — Censo Demográfico 2022 (Variável V0002)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Habitação e Domicílios',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável V0002 (domicílios particulares permanentes ocupados) nos 312 setores censitários municipais.',
    iconName: 'building',
    associatedLayerId: 'setores_censitarios'
  },
  {
    id: 'densidade_demografica_media',
    groupId: 'populacao',
    title: 'Densidade Demográfica Média',
    value: 262.9,
    formattedValue: '262,9',
    unit: 'hab/km²',
    subtitle: 'Relação entre população total e área territorial municipal',
    source: 'Cálculo Oficial Derivado (IBGE 2022)',
    sourceAuthority: 'IBGE / SEPLAN',
    referenceYear: '2022',
    dataType: 'Densidade Demográfica',
    calculationStatus: 'calculado',
    methodology: 'Divisão direta da população residente total pela área territorial oficial do município: 206.215 hab / 784,41 km² = 262,89 hab/km².',
    iconName: 'maximize-2',
    associatedLayerId: 'censo_densidade_2022'
  },
  {
    id: 'rendimento_medio_domiciliar',
    groupId: 'populacao',
    title: 'Rendimento Médio Mensal Domiciliar',
    value: 3895.50,
    formattedValue: 'R$ 3.895,50',
    unit: 'por domicílio',
    subtitle: 'Média setorial apurada pelo Censo 2022 em 307 setores válidos',
    source: 'IBGE — Censo 2022 (Variável V06004 / Redus)',
    sourceAuthority: 'Instituto Brasileiro de Geografia e Estatística (IBGE)',
    referenceYear: '2022',
    dataType: 'Indicador Socioeconômico',
    calculationStatus: 'calculado',
    methodology: 'Média aritmética do rendimento nominal médio mensal domiciliar apurado nos 307 setores censitários municipais com dados válidos.',
    iconName: 'wallet',
    associatedLayerId: 'censo_renda_vulnerabilidade'
  },
  {
    id: 'faixa_etaria_adultos',
    groupId: 'populacao',
    title: 'População Adulta (20 a 59 anos)',
    value: 119496,
    formattedValue: '119.496',
    unit: 'habitantes',
    subtitle: '57,95% da população residente do município',
    source: 'IBGE — Censo 2022 (Variável cn22_pop03_20a59_tot_1)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial cn22_pop03_20a59_tot_1 nos setores censitários do Censo 2022.',
    iconName: 'user-check',
    associatedLayerId: 'censo_pop_20a59'
  },
  {
    id: 'faixa_etaria_idosos',
    groupId: 'populacao',
    title: 'População Idosa (60 anos ou mais)',
    value: 35944,
    formattedValue: '35.944',
    unit: 'habitantes',
    subtitle: '17,43% da população residente municipal (Grupo Prioritário)',
    source: 'IBGE — Censo 2022 (Variável cn22_pop03_m60_tot_1)',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'oficial',
    methodology: 'Soma da variável oficial cn22_pop03_m60_tot_1 nos setores censitários do Censo 2022.',
    iconName: 'heart',
    associatedLayerId: 'censo_pop_m60'
  },
  {
    id: 'faixa_etaria_jovens_criancas',
    groupId: 'populacao',
    title: 'Crianças e Jovens (0 a 19 anos)',
    value: 50775,
    formattedValue: '50.775',
    unit: 'habitantes',
    subtitle: '24,62% da população (0-4: 12.482; 5-9: 13.200; 10-14: 12.560; 15-19: 12.533)',
    source: 'IBGE — Censo Demográfico 2022',
    sourceAuthority: 'IBGE',
    referenceYear: '2022',
    dataType: 'Estrutura Etária',
    calculationStatus: 'derivado',
    methodology: 'Soma das 4 faixas etárias censitárias infantojuvenis oficiais: 12.482 + 13.200 + 12.560 + 12.533 = 50.775 habitantes.',
    iconName: 'baby',
    associatedLayerId: 'censo_pop_0a4'
  }
];
